### ISSUE TITLE
Vragen o.a voor volgende meeting

### ISSUE THREAD

**Issue by MarzSP** [pieter-groenendijk/oose-library-management-system#56]
1. Gaan we logging implementeren?
2. Horen Enums in hun eigen directory Helpers? Momenteel staat mediaType in Model
3. Ik denk dat de Account een teller moet bijhouden voor het aantal niet afgehaalde reserveringen
4.  Ik weet waar de klok is maar niet waar de klepel hangt mbt docker applicaties draaiende te krijgen - servicelaag en webapplicatie
5. Een aantal zaken moeten via DI gebeuren ipv handmatig - het is mij nog niet helemaal helder hoe dit voor elkaar te krijgen, mischien bij jullie wel?
6. Houdt de Controller een referentie naar de service interface ipv direct naar de class zelf?

**Comment by pieter-groenendijk** [comment]
We hadden eerder genoemd dat we de _presentation_ wilde isoleren naar een aparte service. Ik had toen voorgesteld hiermee te helpen. Hier is nog geen (lokale) branch voor aangemaakt of?

**Comment by pieter-groenendijk** [comment]
Ik heb zelf opgeschreven voor deze sprint dat ik het teamproces zal documenteren. Dit is dan samengevat:
- Github
  - PR's
  - Github Project

**Of moet hier nog meer in komen te staan?** Ook over de analyse en design fase enzo?
